$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json

type: pipeline
display_name: animals-pipline-job
description: Pipeline to train an animal classification model.
experiment_name: classification 

# Main compute for the whole job. But we could pick another one. 
compute: azureml:cli-created-machine


jobs:

  dataprep_resize_pandas:
    type: command
    component: ./components/dataprep/dataprep.yaml
    # component: azureml:dataprep:0.1.0 # reference the component by its ID
    inputs: 
      data:
        azureml:Pandas:1
    outputs:
      output_data: 
#        name: pandas_resized
#        version: 1
#        type: uri_folder

  dataprep_resize_cats:
    type: command
    component: ./components/dataprep/dataprep.yaml
    inputs: 
      data:
        azureml:cats:1
    outputs:
      output_data:

  dataprep_resize_dogs:
    type: command
    component: ./components/dataprep/dataprep.yaml
    inputs:
      data:
        azureml:dogs:1
    outputs:
      output_data:

  data_split:
    type: command
    component: ./components/dataprep/train_test_split.yaml
    inputs:
      animal_1: ${{parent.jobs.dataprep_resize_pandas.outputs.output_data}}
      animal_2: ${{parent.jobs.dataprep_resize_cats.outputs.output_data}}
      animal_3: ${{parent.jobs.dataprep_resize_dogs.outputs.output_data}}
      train_test_split_factor: 20
    outputs:
      training_data:
      testing_data:

  training:
    type: command
    component: ./components/training/training.yaml
    inputs:
      training_folder: ${{parent.jobs.data_split.outputs.training_data}}
      testing_folder: ${{parent.jobs.data_split.outputs.testing_data}}
      epochs: 5
      seed: 42
      initial_learning_rate: 0.01
      batch_size: 32
      patience: 11
      model_name: animal-cnn
    outputs:
      output_folder:
        name: animal-clasification
 #       path: azureml://
        type: uri_folder
        mode: upload

  register:
    type: command
    component: azureml://registries/azureml/components/register_model/versions/0.0.9
    inputs:
      model_name: animal-classification
      model_type: custom_model
      model_path: ${{parent.jobs.training.outputs.output_folder}} # This refers to the outputs of the training component in this job
    outputs:
      registration_details_folder: 
        mode: upload 



        


