$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
description: "An environment for training"
name: "training_environment_cli"
version: 0.1.1

conda_file: ../components/training/conda.yaml
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
os_type: linux

tags:
  Pillow: 11.2.1
  Tensorflow: 2.19.0