$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json

name: data_split_cli
type: command
environment: azureml:aml-preprocessing-cli:0.1.0
version: 0.1.0
display_name: Train test split component
description: Split in a train and a test set
is_deterministic: true
resources:
  instance_count: 1

code: ./code 
command: "python traintestsplit.py 
            --datasets ${{inputs.animal_1}} ${{inputs.animal_2}} ${{inputs.animal_3}} 
            --training_data_output ${{outputs.training_data}} 
            --testing_data_output ${{outputs.testing_data}} 
            --split_size ${{inputs.train_test_split_factor}}"
inputs: 
  animal_1:
    type: uri_folder
    optional: False
  animal_2:
    type: uri_folder
    optional: False
  animal_3:
    type: uri_folder
    optional: False
  train_test_split_factor:
    type: number
    optional: False
outputs:
  training_data:
    type: uri_folder
  testing_data:
    type: uri_folder
