name: Azure-test-compute

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



jobs:
  check_azure_version:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure test - Get Compute
        uses: Azure/CLI@v2.1.0
        with:
          azcliversion: 2.75.0
          inlineScript: |
            az extension add --name ml
            az configure --defaults group=${{ secrets.AZURE_RESOURCEGROUP }} workspace=${{ secrets.AZURE_WORKSPACE }} location=${{ secrets.AZURE_LOCATION }}
            az ml compute list

      - name: Azure start up compute
        uses: Azure/CLI@v2.1.0
        with: 
          azcliversion: 2.75.0          
          inlineScript: |
            az extension add --name ml
            az configure --defaults group=${{ secrets.AZURE_RESOURCEGROUP }} workspace=${{ secrets.AZURE_WORKSPACE }} location=${{ secrets.AZURE_LOCATION }}            
            az ml compute create --file ./03_DeployAISolutions/05_MLOps/ai-pipeline/environment/compute.yaml
          continue-on-error: true # Quick fix. If compute already exists, just move on. 
